body {
  background-color: black;
  color: white;
  font-family: sans-serif;
}

h1 {
  text-align: center;
  display: flex;
  justify-content: center;
  flex-wrap: wrap;
}

/* Styles applied to each letter generated by Javascript */
h1 span {
  display: inline-block;
  white-space: pre; 
  animation: wave 2s infinite ease-in-out;
}

/* The animation steps */
@keyframes wave {
  0%, 40%, 100% {
    transform: scale(1);
    color: white;
  }
  20% {
    transform: scale(1.3);     /* Tweens larger */
    color: #4a154b;           /* Turns whitish dark purple */
  }
}
